### ISSUE TITLE
Backend can get product history

### ISSUE THREAD

**Issue by jdcarey128** [jdcarey128/Crate#67]
- [ ] write tests for GraphQL getUserOrders query 
- [ ] write graphQL query for getUserOrders 
- [ ] getUserOrders will return UserOrderType
- [ ] write resolver for getUserOrder query 
- [ ] resolver will have joins with Crates, (user?), and inner joins with products through productDeliveries 

FE #53
