### ISSUE TITLE
Backend setup for user profile update 

### ISSUE THREAD

**Issue by jdcarey128** [jdcarey128/Crate#73]
- [x] add test database in database.json
- [x] store default user image (/public/images/stock)
- [x] run migration to add description, image, and shippingAddress to Users table (set default values)
- [x] update seed file to include updated fields info 
- [x]  add description, image, and shippingAddress in User model (user/model.js)
- [x] add description, image, and shippingAddress for UserType in user/types.js
- [x] write unit tests for User model 

FE #52 
#49 
#54
