### ISSUE TITLE
Backend can set up for product history

### ISSUE THREAD

**Issue by jdcarey128** [jdcarey128/Crate#77]
- [x] run migrations for orders and productDeliveries table 
- [x] add models to setup/models.js
- [x] add files to graphql schema import in setup/schema/mutations and queries.js
- [x] create new module directory order
- [x] within order: create model, resolvers, queries, and types js files 
- [x] define crate model and types 
- [x] crate type will include a list of ProductDeliveryType, and a CrateType (maybe UserType)
- [x] create new module directory productDelivery
- [x] create model and type js files in productDelivery 
- [x] define productDelivery model and type 
- [x] ProductDeliveryType will have a ProductType (import)
- [x] write unit tests for new order and productDelivery models 
- [x] create seed file for dummy data
